# Generated by Django 4.2.13 on 2024-07-19 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_api', '0002_remove_todo_title_todo_task_todo_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='task',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='user',
        ),
        migrations.AddField(
            model_name='todo',
            name='title',
            field=models.CharField(default='test_title', max_length=100),
            preserve_default=False,
        ),
    ]
